---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-sql
data:
  create_usertable.sql: |
    CREATE TABLE IF NOT EXISTS mydb.users (id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, name VARCHAR(50));
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    role: all-in-one
spec:
  containers:
  - name: app-container
    image: masayaaoyama/demo-app:v1.0
    imagePullPolicy: Always
    env:
    - name: DBHOST
      value: 127.0.0.1
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: myuser
    - name: DBPASS
      value: mypass
    - name: DBNAME
      value: mydb
  - name: mysql-container
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: rootpass
    - name: MYSQL_DATABASE
      value: mydb
    - name: MYSQL_USER
      value: myuser
    - name: MYSQL_PASSWORD
      value: mypass
    volumeMounts:
    - name: init-sql-configmap
      mountPath: /docker-entrypoint-initdb.d
  volumes:
    - name: init-sql-configmap
      configMap:
        name: init-db-sql
---
apiVersion: v1
kind: Service
metadata:
  name: demo-all-in-one
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    role: all-in-one
